#!/usr/bin/env python3
import json
from html import escape
from pathlib import Path

ANALYSIS_DATE="2026-06-07"; SKILL_VERSION="1.1.0"; MODEL_VERSION="OpenAI GPT-5.5"
manifest=json.loads(Path("sources/sonova/reports.json").read_text())
HASHES={r["local_file"]:r["sha256"] for r in manifest["reports"]}
REPORTS=[
{"slug":"2026-h1","period":"H1 2025/26","ended":"September 30, 2025","badge":"Strong local growth, weaker cash conversion",
"verdict":"Sonova delivered strong local-currency sales and normalized earnings growth, led by Hearing Instruments and Audiological Care, but Swiss-franc sales declined, reported EBITA fell, free cash flow weakened, and net debt increased.",
"consistency":"Medium: operating performance supported the full-year guidance, but the headline relied heavily on local-currency and normalized measures while reported and cash outcomes were weaker.",
"kpis":[("CHF 1.82B","Sales","-1.0% CHF; +4.9% LC"),("CHF 316M","Normalized EBITA","+16.0% LC; +1.6% CHF"),("CHF 68.9M","Operating FCF","-33.9% YoY"),("CHF 1.35B","Net debt","+CHF 214M since FY")],
"good":["Hearing Instruments and Audiological Care combined grew 7.0% in local currencies, sustaining market-share gains.","Normalized EBITA rose 16.0% in local currencies and normalized margin expanded 180 basis points.","Hearing Instruments sales grew 7.9% and Audiological Care organic sales grew 4.8% in local currencies."],
"bad":["Reported sales declined 1.0% and reported EBITA fell 6.6% in Swiss francs despite strong local-currency framing.","Operating free cash flow fell 33.9% to CHF 68.9 million and free cash flow fell to CHF 37.5 million.","Net debt increased to CHF 1,353.9 million from CHF 1,139.5 million at the prior year-end.","Consumer Hearing sales fell 11.6% and Cochlear Implants system sales fell 6.2% in local currencies."],
"decode":[("“Strong sales and earnings growth”","Accurate in local currencies and normalized EBITA, but not in reported Swiss-franc sales, reported EBITA, or cash flow."),("“Substantial margin improvement”","The normalized local-currency margin improved, while gross margin fell and cash conversion weakened.")],
"bull":"Core hearing businesses continue gaining share and FX pressure eases, allowing local-currency growth to translate into reported earnings and cash.","bear":"Consumer Hearing and Cochlear Implants remain weak while FX, manufacturing changes, and working capital keep suppressing reported results and cash.","watch":"Reported versus local-currency growth; operating free cash flow; net debt; Consumer Hearing; Cochlear Implants system sales.","source":"2026-h1/results-release.md","pages":"1-8"},
{"slug":"2026","period":"FY 2025/26","ended":"March 31, 2026","badge":"Operating leverage rises, cash flow falls",
"verdict":"Sonova delivered above-market local-currency growth and strong normalized EBITA expansion, but reported sales were flat, operating free cash flow fell 11%, and Cochlear Implants remained weak; debt reduction improved the balance sheet despite the cash-flow decline.",
"consistency":"Medium-high: Sonova delivered within guidance and accelerated in the second half, though the planned Consumer Hearing divestment and switch from normalized EBITA to core EBIT complicate future comparisons.",
"kpis":[("CHF 3.61B","Sales","-0.2% CHF; +5.9% LC"),("22.5%","Normalized EBITA margin","+240 bps LC"),("CHF 519M","Operating FCF","-10.8% YoY"),("CHF 994M","Net debt","Down CHF 108M")],
"good":["Organic growth reached 5.4%, with the Hearing Instruments segment growing 6.9% organically.","Normalized EBITA rose 17.3% in local currencies and normalized margin expanded 240 basis points.","Net debt fell to CHF 994.3 million and net debt/EBITDA improved to 1.1x.","Retail organic growth reached 3.8%, exceeding market dynamics."],
"bad":["Reported sales declined 0.2% and normalized EBITA grew only 3.7% in Swiss francs because of severe FX pressure.","Operating free cash flow fell 10.8% and free cash flow fell 7.1%.","Cochlear Implants system sales fell 10.3% in local currencies and normalized EBITA halved.","The Consumer Hearing business was classified as discontinued after continued weakness and a planned divestment."],
"decode":[("“Fully delivering on guidance”","True on guided local-currency measures, while reported sales were flat and cash flow declined."),("“Healthy earnings development”","Operating leverage was strong, but reported-currency growth was modest and cash conversion weakened.")],
"bull":"Product momentum and retail growth sustain share gains, FX pressure moderates, and the Consumer Hearing exit improves focus and profitability.","bear":"FX remains adverse, Cochlear Implants weakness persists, and lower cash conversion limits balance-sheet flexibility.","watch":"FY 2026/27 sales and core EBIT guidance; cash conversion; Cochlear Implants; Consumer Hearing divestment; FX impact.","source":"2026-fy/results-release.md","pages":"1-9"}]
STYLE="*{box-sizing:border-box}body{margin:0;background:#f4f4f6;color:#1f2937;font:13px Arial}.back{display:block;max-width:960px;margin:16px auto}.page{max-width:960px;margin:auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px #0002}.header{background:linear-gradient(135deg,#7d1544,#3b0a25);color:#fff;padding:26px 32px;display:flex;justify-content:space-between}.meta{text-align:right;line-height:1.7}.badge{display:inline-block;padding:3px 10px;border:1px solid #ffffff66;border-radius:20px}.verdict,.consistency{padding:13px 22px;line-height:1.6}.verdict{background:#fff8e1;border-left:5px solid #f59e0b}.consistency{background:#f8fafc;border-left:5px solid #64748b}.kpis{display:grid;grid-template-columns:repeat(4,1fr)}.kpi{text-align:center;padding:16px;border-right:1px solid #ddd}.value{font-size:20px;font-weight:bold;color:#7d1544}.label{font-size:10px;text-transform:uppercase}.content{padding:22px 26px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:26px}h2{font-size:13px;text-transform:uppercase;color:#7d1544;border-bottom:2px solid #ead0dc}.item{line-height:1.55}.decode,.outlook{padding:10px 12px;margin-bottom:8px;background:#fafafa;border-left:3px solid #ccc}.claim{font-style:italic}.sources{padding:0 26px 22px}.footer{display:flex;justify-content:space-between;background:#1a1a2e;color:#9ca3af;padding:11px 24px}.metadata{padding:12px 24px;background:#f9fafb;color:#6b7280;font-size:10px}@media(max-width:720px){.header,.footer{display:block}.meta{text-align:left;margin-top:12px}.kpis,.grid{grid-template-columns:1fr 1fr}}@media(max-width:440px){.kpis,.grid{grid-template-columns:1fr}}"
def render(r):
 link=f'../sources/sonova/{r["source"]}'; cite=f'<a href="{link}">Official results pp. {r["pages"]}</a>'
 items=lambda xs:"".join(f'<p class="item"><strong>{escape(x)}</strong> {cite}</p>' for x in xs)
 kpis="".join(f'<div class="kpi"><div class="value">{escape(a)}</div><div class="label">{escape(b)}</div><div>{escape(c)}</div></div>' for a,b,c in r["kpis"])
 dec="".join(f'<div class="decode"><div class="claim">{escape(a)}</div><div>{escape(b)}</div><div>Confidence: High · {cite}</div></div>' for a,b in r["decode"])
 return f'''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sonova {r["period"]} Investor Report</title><style>{STYLE}</style></head><body><a class="back" href="../companies/sonova.html">Back to Sonova reports</a><main class="page"><header class="header"><div><h1>Sonova Holding AG - {r["period"]} Results</h1><p>Independent, evidence-based investor summary</p></div><div class="meta">Ticker: SOON:SW · SIX Swiss Exchange<br>Period ended {r["ended"]}<br><span class="badge">{r["badge"]}</span></div></header><div class="verdict"><strong>One-line verdict:</strong> {r["verdict"]}</div><div class="consistency"><strong>Historical Consistency Assessment:</strong> {r["consistency"]}</div><div class="kpis">{kpis}</div><div class="content"><div class="grid"><div><section><h2>What Is Genuinely Working</h2>{items(r["good"])}</section><section><h2>Track Record And Consistency</h2><p class="item">{r["consistency"]} {cite}</p></section></div><div><section><h2>What The Headline Obscures</h2>{items(r["bad"])}</section><section><h2>Corporate Language, Decoded</h2>{dec}</section></div></div><section><h2>What To Watch Next</h2><div class="outlook"><p><strong>Bull case:</strong> {r["bull"]}</p><p><strong>Bear case:</strong> {r["bear"]}</p><p><strong>Measurable watchlist:</strong> {r["watch"]}</p></div></section></div><section class="sources"><h2>Sources And Caveats</h2><ul><li><a href="{link}">Official results release</a></li><li><a href="../sources/sonova/INDEX.md">Sonova official source index</a></li><li>Extracted source tables should be checked against the official PDF.</li></ul></section><footer class="footer"><span>Sonova · {r["period"]} · Independent analysis</span><span>Not investment advice</span></footer><div class="metadata">Analysis Date: {ANALYSIS_DATE}<br>Skill Version: {SKILL_VERSION}<br>Model Version: {MODEL_VERSION}<br>Source SHA-256: {HASHES[r["source"]]}</div></main></body></html>'''
def main():
 for r in REPORTS:
  p=Path("reports")/f'sonova-{r["slug"]}.html'; p.write_text(render(r)); print(f"Generated {p}")
if __name__=="__main__": main()
