#!/usr/bin/env python3
"""Download, extract, and index configured official GN financial reports."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
from pathlib import Path

try:
    from scripts.sync_amplifon_reports import extract_markdown, fetch, validate_pdf
except ModuleNotFoundError:
    from sync_amplifon_reports import extract_markdown, fetch, validate_pdf


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "sources" / "gn"
CONFIG_PATH = SOURCE_DIR / "config.json"
MANIFEST_PATH = SOURCE_DIR / "reports.json"
INDEX_PATH = SOURCE_DIR / "INDEX.md"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value: dict) -> None:
    path.write_text(json.dumps(value, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def local_filename(period: str, kind: str) -> str:
    filename = {
        "annual-report": "annual-report.md",
        "interim-report": "interim-report.md",
        "half-year-report": "half-year-report.md",
        "results-release": "results-release.md",
        "results-presentation": "results-presentation.md",
        "conference-call-presentation": "conference-call-presentation.md",
    }[kind]
    return f"{period}/{filename}"


def period_sort_key(report: dict) -> tuple[int, int, str]:
    year, period = report["period"].split("-", 1)
    order = {"q1": 1, "h1": 2, "9m": 3, "fy": 4}
    return int(year), order[period], report["kind"]


def display_period(period: str) -> str:
    year, suffix = period.split("-", 1)
    return f"{suffix.upper()} {year}" if suffix != "fy" else f"FY {year}"


def configured_documents(config: dict) -> list[dict]:
    documents = []
    for document in config["documents"]:
        normalized = dict(document)
        normalized["local_file"] = local_filename(document["period"], document["kind"])
        documents.append(normalized)
    return documents


def generate_index(manifest: dict, config: dict) -> str:
    lines = [
        f'# {config["company"]} Source Reports',
        "",
        "Official GN investor materials downloaded from",
        f'[{config.get("official_domain", config["company"])}]({config["index_url"]}).',
        "",
        "PDFs are downloaded temporarily, checksum-verified, and converted to page-marked",
        "Markdown. The original PDF remains available through its official download URL.",
        "",
        f'This file is generated by `{config.get("sync_command", "python3 scripts/sync_gn_reports.py")}` from',
        "[config.json](config.json) and [reports.json](reports.json).",
        "",
        "## Reports",
        "",
        "| Period | Document | Downloaded | Local file | Official download URL |",
        "| --- | --- | --- | --- | --- |",
    ]
    for report in sorted(manifest["reports"], key=period_sort_key):
        lines.append(
            f'| {display_period(report["period"])} | {report["title"]} | '
            f'{report["downloaded_at"]} | [{Path(report["local_file"]).name}]'
            f'({report["local_file"]}) | [Download]({report["source_url"]}) |'
        )
    lines.extend(["", "## Official Index", "", f'- [{config["company"]} financial reports]({config["index_url"]})'])
    return "\n".join(lines) + "\n"


def verify_manifest(manifest: dict) -> None:
    for report in manifest["reports"]:
        path = SOURCE_DIR / report["local_file"]
        if not path.is_file():
            raise FileNotFoundError(f"Manifest file is missing: {path}")
        extracted = path.read_text(encoding="utf-8")
        if "<!-- page: 1 -->" not in extracted or report["source_url"] not in extracted:
            raise ValueError(f"Markdown extract metadata is invalid: {path}")


def sync(download_date: str, check: bool = False) -> int:
    config = load_json(CONFIG_PATH)
    manifest = load_json(MANIFEST_PATH)
    known_urls = {report["source_url"] for report in manifest["reports"]}
    known_keys = {(report["period"], report["kind"]) for report in manifest["reports"]}
    additions = []

    for document in configured_documents(config):
        key = (document["period"], document["kind"])
        if document["source_url"] in known_urls:
            continue
        if key in known_keys:
            raise ValueError(f"Duplicate configured GN document for {key}")
        additions.append(document)
        known_keys.add(key)

    if check:
        if additions:
            for document in additions:
                print(f'New report available: {document["period"]} {document["kind"]} {document["source_url"]}')
            return 1
        print("No new reports found.")
        return 0

    for document in additions:
        data = fetch(document["source_url"])
        validate_pdf(data, document["source_url"])
        report = {
            **document,
            "downloaded_at": download_date,
            "size_bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
        }
        destination = SOURCE_DIR / report["local_file"]
        if destination.exists():
            raise FileExistsError(f"Refusing to overwrite {destination}")
        extract_markdown(data, destination, report)
        manifest["reports"].append(report)
        print(f'Downloaded and extracted {report["title"]} to {report["local_file"]}')

    manifest["reports"].sort(key=period_sort_key)
    verify_manifest(manifest)
    write_json(MANIFEST_PATH, manifest)
    INDEX_PATH.write_text(generate_index(manifest, config), encoding="utf-8")
    print(f"Indexed {len(manifest['reports'])} reports; added {len(additions)}.")
    return 0


def refresh_extracts() -> None:
    manifest = load_json(MANIFEST_PATH)
    for report in manifest["reports"]:
        data = fetch(report["source_url"])
        validate_pdf(data, report["source_url"])
        if hashlib.sha256(data).hexdigest() != report["sha256"] or len(data) != report["size_bytes"]:
            raise ValueError(f"Official PDF changed for {report['source_url']}")
        extract_markdown(data, SOURCE_DIR / report["local_file"], report)
        print(f'Refreshed {report["local_file"]}')
    verify_manifest(manifest)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report whether configured documents are not yet downloaded")
    parser.add_argument("--refresh-extracts", action="store_true", help="Regenerate Markdown from verified source PDFs")
    parser.add_argument("--date", default=dt.date.today().isoformat(), help="Download date recorded for new files")
    args = parser.parse_args()
    if args.refresh_extracts:
        refresh_extracts()
        return 0
    return sync(args.date, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
